import {
  SiAndroid,
  SiAndroidstudio,
  SiAngular,
  SiApachetomcat,
  SiDotnet,
  SiFlask,
  SiGooglecolab,
  SiJenkins,
  SiJetpackcompose,
  SiJupyter,
  SiKotlin,
  SiNumpy,
  SiOpenjdk,
  SiPandas,
  SiPlotly,
  SiPython,
  SiPytorch,
  SiSpring,
  SiSqlite,
  SiStreamlit,
  SiTensorflow,
  SiXml,
  SiDocker,
  SiLinkedin,
  SiMongodb,
} from "react-icons/si";

export const TOOL_ICONS: Record<string, React.ComponentType<{ className?: string }>> = {
  openjdk: SiOpenjdk,
  spring: SiSpring,
  angular: SiAngular,
  dotnet: SiDotnet,
  xml: SiXml,
  apachetomcat: SiApachetomcat,
  jenkins: SiJenkins,
  python: SiPython,
  pytorch: SiPytorch,
  flask: SiFlask,
  googlecolab: SiGooglecolab,
  jupyter: SiJupyter,
  yolov8: SiPytorch,
  kotlin: SiKotlin,
  android: SiAndroid,
  androidstudio: SiAndroidstudio,
  jetpackcompose: SiJetpackcompose,
  csharp: SiDotnet,
  aspnetcore: SiDotnet,
  razorpages: SiDotnet,
  sqlite: SiSqlite,
  streamlit: SiStreamlit,
  pandas: SiPandas,
  plotly: SiPlotly,
  tensorflow: SiTensorflow,
  keras: SiTensorflow,
  numpy: SiNumpy,
  docker: SiDocker,
  matplotlib: SiPython,
  mongodb: SiMongodb,
  nosql: SiMongodb,
};

export const TOOL_ICON_URLS: Record<string, string> = {
  microsoftsqlserver:
    "https://cdn.jsdelivr.net/gh/devicons/devicon/icons/microsoftsqlserver/microsoftsqlserver-plain.svg",
};
